import {
  chillhits,
  classicRock,
  hits80,
  megaHits,
  rapcaviar,
  todayTop,
  top2010,
  vivaLatino,
  spotify,
  card,
  alone,
  madrid,
  arca10Mil,
  nonstop,
  pokerface,
  liberianGirl,
  greedy,
  dreams,
  alaneva,
  arcangel,
  anamena,
  drake,
  ladygaga,
  michael,
  tate,
  thecamberries,
  chill,
  pop,
  rock,
  latino,
  workout,
  danceelectronic,
  flamenco,
  foryou,
  liveEvents,
  podcast,
  hiphop,
  newrelease,
  party,
  classic,
  decades,
  instrumental,
  gaming,
  trending,
} from "../assets";

const randomPlaylist = [
  {
    title: "Today's Top Hits",
    desc: "Tate McRae is on top of the Hottest 50!",
    image: todayTop,
  },
  {
    title: "RapCaviar",
    desc: "New music from Drake, Lil Wayne and 2 Chainz.",
    image: rapcaviar,
  },
  {
    title: "All Out 2010s",
    desc: "The biggest songs of the 2010s.",
    image: top2010,
  },
  {
    title: "Rock Classics",
    desc: "Rock legends & epic songs that continue to inspire..",
    image: classicRock,
  },
  {
    title: "Chill Hits",
    desc: "Kick back to the best new and recent chill hits.",
    image: chillhits,
  },
  {
    title: "Viva Latino",
    desc: "Today's top Latin hits, elevando nuestra música..",
    image: vivaLatino,
  },
  {
    title: "Mega Hit Mix",
    desc: "A mega mix of 75 favorites from the lst few years!",
    image: megaHits,
  },
  {
    title: "All Out 80s",
    desc: "The biggest songs of the 1980s. Cover: Michael..",
    image: hits80,
  },
];

const randomSongs = [
  {
    id: Math.random() * Date.now(),
    title: "Greedy",
    artist: "Tate McRae",
    image: tate,
    mp3: new Audio(greedy),
  },

  {
    id: Math.random() * Date.now(),
    title: "NonStop",
    artist: "Drake",
    image: drake,
    mp3: new Audio(nonstop),
  },
  {
    id: Math.random() * Date.now(),
    title: "Poker Face",
    artist: "Lady Gaga",
    image: ladygaga,
    mp3: new Audio(pokerface),
  },
  {
    id: Math.random() * Date.now(),
    title: "Dreams",
    artist: "The Camberries",
    image: thecamberries,
    mp3: new Audio(dreams),
  },
  {
    id: Math.random() * Date.now(),
    title: "Alone",
    artist: "Alan Walker & Ava Max",
    image: alaneva,
    mp3: new Audio(alone),
  },
  {
    id: Math.random() * Date.now(),
    title: "Arca 10 Mil",
    artist: "Arcangel & Feid",
    image: arcangel,
    mp3: new Audio(arca10Mil),
  },
  {
    id: Math.random() * Date.now(),
    title: "Madrid City",
    artist: "Ana Mena",
    image: anamena,
    mp3: new Audio(madrid),
  },
  {
    id: Math.random() * Date.now(),
    title: "Liberian Girl",
    artist: "Michael Jackson",
    image: michael,
    mp3: new Audio(liberianGirl),
  },
];
const categories = [
  {
    title: "Podcast",
    image: podcast,
    bgColor: "#006450",
  },

  {
    title: "Live Events",
    image: liveEvents,
    bgColor: "#8400e7",
  },
  {
    title: "Made For You",
    image: foryou,
    bgColor: "#1e3264",
  },
  {
    title: "New Releases",
    image: newrelease,
    bgColor: "#e8115b",
  },
  {
    title: "Latin",
    image: latino,
    bgColor: "#E1118C",
  },
  {
    title: "Pop",
    image: pop,
    bgColor: "#148A08",
  },
  {
    title: "Rock",
    image: rock,
    bgColor: "#E91429",
  },
  {
    title: "Hip-Hop",
    image: hiphop,
    bgColor: "#503750",
  },
  {
    title: "Flamenco",
    image: flamenco,
    bgColor: "#E91429",
  },
  {
    title: "Dance/Electronic",
    image: danceelectronic,
    bgColor: "#D84000",
  },
  {
    title: "Workout",
    image: workout,
    bgColor: "#777777",
  },
  {
    title: "Chill",
    image: chill,
    bgColor: "#006450",
  },
  {
    title: "Party",
    image: party,
    bgColor: "#537AA1",
  },
  {
    title: "Decades",
    image: decades,
    bgColor: "#BA5D07",
  },
  {
    title: "Gaming",
    image: gaming,
    bgColor: "#E8115B",
  },
  {
    title: "Classic",
    image: classic,
    bgColor: "#7D4B32",
  },
  {
    title: "Instrumental",
    image: instrumental,
    bgColor: "#537AA1",
  },
  {
    title: "Trending",
    image: trending,
    bgColor: "#537AA1",
  },
];
export { randomPlaylist, spotify, randomSongs, categories };
